#!/usr/bin/env php
<?php
// app/console

require dirname(__DIR__) . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

use Anspi\AnspiBundle\Command\ConfigureCommand;
use Anspi\AnspiBundle\Command\UtilsCommand;

$application = new Application();

$application->add(new ConfigureCommand());
$application->add(new UtilsCommand());

$application->run();
